version: '3'

services:
  server:
    container_name: fast-server
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    environment: 
      - FLASK_APP=main.py
      - FLASK_ENV=development
    volumes: 
      - ./src:/app
  db:
    container_name: fast-db
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fast
    ports:
      - 3306:3306
    volumes:
      - ./fast.sql:/docker-entrypoint-initdb.d/fast.sql
